language: minimal 

sudo: required
services:
  - docker

before_install:
  - docker build -t goodfaith/docker-react -f Dockerfile.dev .

script:
  - docker run goodfaith/docker-react npm run test -- --coverage

