# Specify base image
FROM node:alpine

# Create container working directory 
WORKDIR '/app'

# Install Node dependencies
COPY ./package.json ./
RUN npm install
COPY ./ ./

# Default command
CMD ["npm", "run", "start"]